### PR TITLE
Update users.json

### PR DESCRIPTION
**Pull request by Subh2410**
Request to add GitHub username to list of codex members

### CODE REVIEW

**Comment by Zanark** [comment]
maintain the indentation

**Comment by Subh2410** [comment]
> maintain the indentation

> maintain the indentation

Need to send it again?

**Comment by SubhrajitPrusty** [comment]
You can edit files from this PR itself

**Comment by Zanark** [comment]
@SubhrajitPrusty why re the checks failing tho

**Comment by Subh2410** [comment]
> You can edit files from this PR itself

sent it again

**Comment by Zanark** [comment]
@Subh2410 an entry should be followed by a `,`

**Comment by Subh2410** [comment]
> @Subh2410 an entry should be followed by a `,`

not getting it!

**Comment by SubhrajitPrusty** [comment]
@Zanark added some default auto actions, trying to figure out why it's failing

**Comment by SubhrajitPrusty** [comment]
ignore: closing and reopening to check labeler

**Comment by Zanark** [comment]
@Subh2410 look up JSON syntax online

**Comment by SubhrajitPrusty** [comment]
fixed it myself.

**Pull request merged**
