### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Ankit289Prasad**

### CODE REVIEW

**Comment by SubhrajitPrusty** [comment]
You also need to update the `users.json` file

See #17

**Review by SubhrajitPrusty — CHANGES_REQUESTED** [review]
See #17 

Update `users.json`

**Comment by Ankit289Prasad** [comment]
okay :+1:

**Comment by SubhrajitPrusty** [comment]
**Do not** close PRs on your own. You can make changes in the same branch for the same PR.

**Pull request closed without merging**
